site_name: CTF Handbook
site_description: Capture the Flag Competition Wiki
site_author: OSIRIS Lab & CTFd LLC
plugins:
  - search
  - exclude-search:
      exclude:
        - challenges/*
  - git-revision-date-localized:
      enable_creation_date: true
#       type: timeago
#       locale: en
#       fallback_to_build_date: false
#       enable_creation_date: true
#       exclude:
#           - index.md
#       enabled: true
#       strict: true
theme:
  name: material
  favicon: images/favicon/favicon.ico
  logo: images/ctf101.png
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
  features:
    # - navigation.tabs
    # - navigation.sticky
    - navigation.instant
    - content.code.annotate
    # - navigation.sections
    # - navigation.expand
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Automatic light-dark mode toggling

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    code: Roboto Mono

extra_css:
- stylesheets/extra.css

extra:
  generator: false
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/osirislab
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Vk6RXcw5wx
copyright: Made with â™¥ by OSIRIS Lab & CTFd

repo_url: https://github.com/osirislab/ctf101
repo_name: osiris/ctf101
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

docs_dir: docs/
nav:
# This does not show up on the navbar. The Index word is specifically hidden in nav.html
- Home: index.md

- Start Here:
  - What is a CTF: 'start-here/what-is-a-ctf.md'
  - How do I host a CTF: 'start-here/how-to-run-a-ctf.md'
  


# Forensics Section
- Forensics:
  - Overview: 'forensics/overview.md'
  - File Formats:
    - What are File Formats: 'forensics/what-are-file-formats.md'
  - Metadata:
    - What is Metadata: 'forensics/what-is-metadata.md'
  - Wireshark:
    - What is Wireshark: 'forensics/what-is-wireshark.md'
  - Steganography:
    - What is Steganography: 'forensics/what-is-stegonagraphy.md'
  - Disk Imaging:
    - What is Disk Imaging: 'forensics/what-is-disk-imaging.md'
  - Memory Forensics:
    - What is Memory Forensics: 'forensics/what-is-memory-forensics.md'
  - Hex Editors:
    - What is a Hex Editor: 'forensics/what-is-a-hex-editor.md'


# Cryptography Section
- Cryptography:
  - Overview: 'cryptography/overview.md'
  - XOR:
    - What is XOR: 'cryptography/what-is-xor.md'
  - Substitution Cipher:
    - What is a Substitution Cipher: 'cryptography/what-is-a-substitution-cipher.md'
    - Caesar Cipher/ROT 13: 'cryptography/what-is-caesar-cipher-rot-13.md'
  - Vigenere Cipher:
    - What is a Vigenere Cipher: 'cryptography/what-is-a-vigenere-cipher.md'
  - Hashing Functions:
    - What are Hashing Functions: 'cryptography/what-are-hashing-functions.md'
  - Modes of Operation:
    - What are Block Ciphers: 'cryptography/what-are-block-ciphers.md'
    - What are Stream Ciphers: 'cryptography/what-are-stream-ciphers.md'
  - RSA:
    - What is RSA: 'cryptography/what-is-rsa.md'


# Web Exploitation Section
- Web Exploitation:
  - Overview: 'web-exploitation/overview.md'
  - SQL Injection:
    - What is SQL Injection: 'web-exploitation/sql-injection/what-is-sql-injection.md'
  - Command Injection:
    - What is Command Injection: 'web-exploitation/command-injection/what-is-command-injection.md'
  - Directory Traversal:
    - What is Directory Traversal: 'web-exploitation/directory-traversal/what-is-directory-traversal.md'
  - Cross Site Request Forgery:
    - What is Cross Site Request Forgery: 'web-exploitation/cross-site-request-forgery/what-is-cross-site-request-forgery.md'
  - Cross Site Scripting (XSS):
    - What is Cross Site Scripting: 'web-exploitation/cross-site-scripting/what-is-cross-site-scripting.md'
  - Server Side Request Forgery:
    - What is Server Side Request Forgery: 'web-exploitation/server-side-request-forgery/what-is-server-side-request-forgery.md'
  - PHP:
    - What is PHP?: 'web-exploitation/php/what-is-php.md'


# Reverse Engineering Section
- Reverse Engineering:
  - Overview: 'reverse-engineering/overview.md'
  - Assembly/Machine Code:
    - What is Assembly/Machine Code: 'reverse-engineering/what-is-assembly-machine-code.md'
  - The C Programming Language:
    - What is C: 'reverse-engineering/what-is-c.md'
  - Disassemblers:
    - What are Disassemblers: 'reverse-engineering/what-are-disassemblers.md'
  - Debuggers:
    - What is GDB: 'reverse-engineering/what-is-gdb.md'
  - Decompilers:
    - What are Decompilers: 'reverse-engineering/what-are-decompilers.md'


#  Binary Exploitation Section
- Binary Exploitation:
  - Overview: 'binary-exploitation/overview.md'
  - Registers:
    - What are Registers: 'binary-exploitation/what-are-registers.md'
  - The Stack:
    - What is the Stack: 'binary-exploitation/what-is-the-stack.md'
  - Calling Conventions:
    - What are Calling Conventions: 'binary-exploitation/what-are-calling-conventions.md'
  - Global Offset Table (GOT):
    - What is the GOT: 'binary-exploitation/what-is-the-got.md'
  - Buffers:
    - What are Buffers: 'binary-exploitation/what-are-buffers.md'
    - Buffer Overflow: 'binary-exploitation/buffer-overflow.md'
  - Return Oriented Programming (ROP):
    - What is ROP: 'binary-exploitation/return-oriented-programming.md'
  - Binary Security:
    - What is Binary Security: 'binary-exploitation/what-is-binary-security.md'
    - No eXecute (NX): 'binary-exploitation/no-execute.md'
    - Address Space Layout Randomization (ASLR): 'binary-exploitation/address-space-layout-randomization.md'
    - Stack Canaries: 'binary-exploitation/stack-canaries.md'
    - Relocation Read-Only (RELRO): 'binary-exploitation/relocation-read-only.md'
  - The Heap:
    - What is the Heap: 'binary-exploitation/what-is-the-heap.md'
    - Heap Exploitation: 'binary-exploitation/heap-exploitation.md'
  - Format String Vulnerability:
    - What is a Format String Vulnerability: 'binary-exploitation/what-is-a-format-string-vulnerability.md'

- FAQ:
  - How to connect to services: 'faq/connecting-to-services.md'
  - I need a server: 'faq/i-need-a-server.md'
  - Recommended Software: 'faq/recommended-software.md'
